services:
  cassandra:
    image: cassandra:4.1
    container_name: cassandra
    ports:
      - "9042:9042"
    volumes:
      - ./db-init/cassandra:/docker-entrypoint-initdb.d
    environment:
      - CASSANDRA_CLUSTER_NAME=chargeback-cluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_HOSTS=localhost
      - CASSANDRA_BROADCAST_ADDRESS=127.0.0.1
      - CASSANDRA_START_RPC=true
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch

  cassandra-init:
    image: cassandra:4.1
    depends_on:
      - cassandra
    volumes:
      - ./db-init/cassandra/schema.cql:/docker-entrypoint-initdb.d/schema.cql
      - ./db-init/cassandra/init.sh:/docker-entrypoint-initdb.d/init.sh
    entrypoint: [ "/bin/sh", "/docker-entrypoint-initdb.d/init.sh" ]

  batch-files:
    image: postgres:15
    container_name: batch-files
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: batch
    volumes:
      - batch_files_data:/var/lib/postgresql/data
      - ./db-init/postgres/schema.sql:/docker-entrypoint-initdb.d/init.sql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    volumes:
      - minio-data:/data

  mastercard:
    image: stilliard/pure-ftpd:hardened
    container_name: mastercard
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    environment:
      - FTP_USER_NAME=admin
      - FTP_USER_PASS=admin
      - FTP_USER_HOME=/home/ftpusers/admin
      - PASV_MIN_PORT=30000
      - PASV_MAX_PORT=30009
      - PUBLICHOST=127.0.0.1
    volumes:
      - mastercard-data:/home/ftpusers

  chargeback-api:
    build:
      context: ./../chargeback-api
      dockerfile: chargeback-api.dockerfile
    container_name: chargeback-api
    restart: always
    ports:
      - "8080:80"
    environment:
      CASSANDRA_HOSTS: "cassandra"
      CASSANDRA_KEYSPACE: "chargebacks"
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"
      NEW_RELIC_LICENSE_KEY: ""
      NEW_RELIC_ENABLED: false
    depends_on:
      - cassandra
      - rabbitmq

  chargeback-processor:
    build:
      context: ./../chargeback-processor
      dockerfile: chargeback-processor.dockerfile
    container_name: chargeback-processor
    restart: always
    environment:
      CASSANDRA_HOSTS: "cassandra"
      CASSANDRA_KEYSPACE: "chargebacks"
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"
      NEW_RELIC_LICENSE_KEY: ""
      NEW_RELIC_ENABLED: false
      MINIO_ENDPOINT: "minio:9000"
      MINIO_ACCESS_KEY: "admin"
      MINIO_SECRET_KEY: "password"
      MINIO_BUCKET_NAME: "chargebacks"
      CHARGEBACK_OUTPUT_DIR: "/tmp/chargebacks"
      CHARGEBACK_MAX_DURATION_VALUE: "1"
      CHARGEBACK_MAX_DURATION_UNIT: "minutes" # "seconds" ou "minutes", ou "hours"
      CHARGEBACK_MAX_RECORDS: "2500"
    volumes:
      - ./local-output:/tmp/chargebacks
    depends_on:
      - cassandra
      - rabbitmq
      - minio

  chargeback-batch:
    build:
      context: ./../chargeback-batch
      dockerfile: chargeback-batch.dockerfile
    container_name: chargeback-batch
    restart: always
    environment:
      DSN: "host=batch-files port=5432 user=admin password=admin dbname=batch sslmode=disable timezone=UTC connect_timeout=5"
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672/"
      MINIO_ENDPOINT: "minio:9000"
      MINIO_ACCESS_KEY: "admin"
      MINIO_SECRET_KEY: "password"
      MINIO_BUCKET_NAME: "chargebacks"
      FTP_HOST: "mastercard"
      FTP_PORT: 21
      FTP_USER: "admin"
      FTP_PASS: "admin"
      SCHEDULER_ENABLED: true
      SCHEDULER_INTERVAL_VALUE: "5"
      SCHEDULER_INTERVAL_UNIT: "minutes" # "seconds" ou "minutes", ou "hours"
      BATCH_MAX_FILES_PER_DAY: 4
      NEW_RELIC_LICENSE_KEY: ""
      NEW_RELIC_ENABLED: false
    volumes:
      - batch_files_data:/var/lib/postgresql/data
      - ./db-init/postgres/schema.sql:/docker-entrypoint-initdb.d/init.sql
      - ./local-batch-output:/tmp/chargebacks
    depends_on:
      - batch-files
      - rabbitmq
      - minio
      - mastercard


volumes:
  cassandra-data:
  rabbitmq-data:
  minio-data:
  batch_files_data:
  mastercard-data:
