services:
  cassandra:
    image: cassandra:4.1
    container_name: cassandra
    ports:
      - "9042:9042"
    volumes:
      - ./db-init/cassandra:/docker-entrypoint-initdb.d
    environment:
      - CASSANDRA_CLUSTER_NAME=chargeback-cluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_HOSTS=localhost
      - CASSANDRA_BROADCAST_ADDRESS=127.0.0.1
      - CASSANDRA_START_RPC=true
      - CASSANDRA_RPC_ADDRESS=0.0.0.0
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=password
    volumes:
      - minio-data:/data

  batch-files:
    image: postgres:15
    container_name: batch-files
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: batch
    volumes:
      - batch_files_data:/var/lib/postgresql/data
      - ./db-init/postgres/schema.sql:/docker-entrypoint-initdb.d/init.sql

#  chargeback-api:
#    build:
#      context: ./../chargeback-api
#      dockerfile: chargeback-api.dockerfile
#    container_name: chargeback-api
#    restart: always
#    ports:
#      - "8080:80"
#    environment:
#      CASSANDRA_HOSTS: "cassandra"
#      CASSANDRA_KEYSPACE: "chargebacks"
#      RABBITMQ_URL: "amqp://admin:admin@rabbitmq:5672/"
#      NEW_RELIC_LICENSE_KEY: ""
#      S3_ENDPOINT: "http://minio:9000"
#      S3_ACCESS_KEY: "admin"
#      S3_SECRET_KEY: "password"
#    depends_on:
#      - cassandra
#      - rabbitmq
#      - minio

volumes:
  cassandra-data:
  rabbitmq-data:
  minio-data:
  batch_files_data:
